### ISSUE TITLE
Repo broken

### ISSUE THREAD

**Issue by huskynp** [CrushingStar/hello-world#1]
This repo doesn't work when I try to download it and has been unmaintained for a while. Can the developer please post an update? Having this repo up-to-date would greatly help me and my development team.

**Comment by CrushingStar** [comment]
No u

**Comment by huskynp** [comment]
I really need this repo fixed. Please do something, CrushingStar, otherwise I'm going to have to makemy own repo and give this one a one-star review.

**Comment by huskynp** [comment]
@CrushingStar I've created a PR that addresses most of my concerns with the repo and makes it usable and up-to-date with current standards. I'm happy to on-and-off maintain this project in a fork if you can't, just accept the PR and let me know.

**Comment by CrushingStar** [comment]
bannable
